
modLoader="javafml"
loaderVersion="[1,)"
license="MIT"


[[mods]]
    modId="ae2ao"

    version="${file.jarVersion}"
    displayName="AE2AO"
    logoFile="logo.png"

    authors="DomamaN202, PashkovD"

    description="AE2 addon"


[[dependencies.ae2ao]]
    modId="appliedenergistics2"
    mandatory=true
    versionRange="[9.0.0-alpha.1,10)"
    ordering="AFTER"
    side="BOTH"

