
modLoader="javafml"
loaderVersion="[1,)"
license="MIT"


[[mods]]
    modId="ae2ao"

    version="${file.jarVersion}"
    displayName="AE2AO"
    logoFile="logo.png"

    authors="DomamaN202, PashkovD"

    description="AE2 addon"


[[dependencies.ae2ao]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ae2ao]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ae2ao]]
    modId="ae2"
    mandatory=true
    versionRange="[12,13)"
    ordering="AFTER"
    side="BOTH"

