
modLoader="javafml"
loaderVersion="[1,)"
license="MIT"


[[mods]]
    modId="ae2ao"

    version="${file.jarVersion}"
    displayName="AE2AO"
    logoFile="logo.png"

    authors="DomamaN202, PashkovD"

    description="AE2 addon"


[[dependencies.ae2ao]]
    modId = "ae2"
    mandatory = false
    versionRange = "[15,16)"
    ordering = "AFTER"
    side = "BOTH"

